add_library(lili_dsp STATIC src/Engine.cpp)
add_library(lili::dsp ALIAS lili_dsp)
target_include_directories(lili_dsp PUBLIC include)
target_compile_features(lili_dsp PUBLIC cxx_std_20)
set_target_properties(lili_dsp PROPERTIES POSITION_INDEPENDENT_CODE ON)

if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
    target_compile_options(lili_dsp PRIVATE -Wall -Wextra -Wpedantic -Wshadow -Wconversion -Wno-sign-conversion)
    if(LILI_WARNINGS_AS_ERRORS)
        target_compile_options(lili_dsp PRIVATE -Werror)
    endif()
elseif(MSVC)
    target_compile_options(lili_dsp PRIVATE /W4 $<$<BOOL:${LILI_WARNINGS_AS_ERRORS}>:/WX>)
endif()
